spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka/,http://eureka1:2002/eureka
